name: mnn
description: A package for running MNN models on Dart and Flutter.
version: 0.0.3
mnn_version: 3.2.1
repository: https://github.com/rainyl/mnn.dart

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.4
  logging: ^1.3.0
  meta: ^1.16.0
  hooks: ">=0.19.5 <0.21.0"
  native_toolchain_cmake: ">=0.0.6-dev.0 <0.2.0"
  # native_toolchain_cmake:
  #   path: ../native_toolchain_cmake
  path: ^1.9.1
  yaml: ^3.1.3
  code_assets: ^0.19.0

dev_dependencies:
  ffigen: ^19.0.0
  image: ^4.5.4
  lints: ">=5.0.0 <7.0.0"
  test: ^1.24.0

topics:
  - mnn
  - machine-learning
  - deep-learning
  - native-assets
