name: mnn
description: A package for running MNN models on Dart and Flutter.
version: 0.1.1
mnn_version: 3.3.0
repository: https://github.com/rainyl/mnn.dart

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  logging: ^1.3.0
  meta: ^1.16.0
  native_toolchain_cmake: ^0.2.2
  # native_toolchain_cmake:
  #   path: ../native_toolchain_cmake
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  ffigen: ^20.1.1
  image: ^4.7.2
  lints: ^6.0.0
  test: ^1.24.0

topics:
  - mnn
  - machine-learning
  - deep-learning
  - native-assets

hooks:
  user_defines:
    mnn:
      options:
        build_local: false
        debug: true
      defines:
        common:
          MNN_SUPPORT_BF16: ON
          MNN_BUILD_OPENCV: ON
          MNN_LOW_MEMORY: OFF
        macos:
          MNN_METAL: ON
        android:
          MNN_DEBUG: OFF
          MNN_GPU_TRACE: ON
          MNN_OPENCL: ON
          MNN_OPENGL: ON
          MNN_VULKAN: OFF
          MNN_VULKAN_DEBUG: ON
          MNN_ARM82: ON
          MNN_USE_SYSTEM_LIB: ON
